# Generated by Django 5.0.7 on 2024-07-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Addemployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("age", models.IntegerField()),
                ("photo", models.ImageField(upload_to="Profile-Image")),
                ("department", models.CharField(max_length=200)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("gender", models.CharField(max_length=10)),
                ("phone_number", models.CharField(max_length=15)),
                ("address", models.CharField(max_length=200)),
                ("join_date", models.DateField()),
                ("position", models.CharField(max_length=200)),
                (
                    "employee_id",
                    models.CharField(blank=True, max_length=6, unique=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
